"""v2_task_model

Revision ID: b5e0cb2ec827
Revises: 9df272121efc
Create Date: 2026-06-26 14:59:36.422592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e0cb2ec827'
down_revision: Union[str, Sequence[str], None] = '9df272121efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tasks', sa.Column('task_type', sa.String(), server_default='task', nullable=False))
    op.add_column('tasks', sa.Column('dependency_type', sa.String(), server_default='FS', nullable=True))
    op.add_column('tasks', sa.Column('lag_days', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tasks', sa.Column('estimated_hours', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('tasks', sa.Column('actual_hours', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('tasks', sa.Column('remaining_hours', sa.Float(), server_default='0.0', nullable=False))
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_column('tasks', 'remaining_hours')
    op.drop_column('tasks', 'actual_hours')
    op.drop_column('tasks', 'estimated_hours')
    op.drop_column('tasks', 'lag_days')
    op.drop_column('tasks', 'dependency_type')
    op.drop_column('tasks', 'task_type')
    op.drop_column('tasks', 'progress')
    # ### end Alembic commands ###
